sudo: required
language: node_js
node_js:
- 8
services:
- docker
cache:
  directories:
  - node_modules
script:
- npm test
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "dev" ]]; then
  docker build -t cangr/mvs-explorer-api:dev .; docker push cangr/mvs-explorer-api:dev;
  fi
- if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then
  docker build -t cangr/mvs-explorer-api:latest .; docker push cangr/mvs-explorer-api:latest;
  fi
env:
  global:
  - secure: GBq+cB3LUrK5A3F18WbZkZcR5ggPkX1bGU0gC0C1A3REy6DWr8fnc6esaxIYuaK13VZtH6enFb//uz6d2V7qHj3zHzdPknqlxWusW6At3tvpHiqcpoYQEA7+fNvq3TmXRP3WpJW1Xle067/gZfz4PYC1cnIoJnRAznPwgMxJ7tUwBrCdfocQiBa1eIxvyTQkKVqCXJxr/qoLmSqggGO/FFVWU8L5tOT8n4rmW1VUXFJogq1xpevGYTjju9k1g+MH2WqIFfAXoAxppL0yZ81/5ICU6Z/TN2jM1387snSWN6792O0xHKq4sTPJiiYFOYLMUZILr3VzJFHu+jfdRO6S+k4kjVbpMaGcjX8E4HAz7rTKXU3k2tQbG1x1TS9O+zVBUCae/Y8Up5g80XGD11rxhbpMSCu1AwDwihYa2KBiHe1YEaN98Bzk0HpULNq/g7pPAJ7KMWPSUTQWs4yy8NISJTowpMkKn1sQUeqyyPaPgbYW6dYAEyxSbHi5uQQEAzUCVnTopNY62ETNwGs+8yfebTJue2f/FeoJbp+08uXxv7BStSiWSct3nJTscpn7pD6DC86lo+VAR2K+PbrKeKXvLblI+B7vqvBybsZGvym+bvzPIR5VRgRwAnMx1HK08jS8E4WtYOZNqQeZ2iRtqrHiIUXeDI0ERC0io7KnLTXT07M=
  - secure: b4trUih9fmz/k5BgS2VjkMaocfCGkfHOhUEOYOj+lIF+w0Vhlbsm+uPzviTrHNdiXe8+z+1qtmgMLm4LeChYBkxb6trG92DkMxIWk3baLjbhjMy3W6wkW54/JdXcpgjKSfaBLJsJIlVyPj7KpyVh+rJrTO67blf3n5bLXR79bEy8p7T1j5LEoapM60LFDO3IFlkv4HiZaBYaZ8UFLoCqVcAcprUDsPcDc2KTSmPdFnpoTRAeH9Ftz2iHmzv9g1QsTqalpjQ2QvMU8+HYEDapjy4qXY99OBlrK/2DVlQ7q4bpU1Kx1wY5sH/CpnzYFpRvq0in5iiQQLZtQMYtCVT45lw+w0UXeZ0dMMsmBuRHlV9QB8JO5YjMAo4vHJHYrfxwDMBdgTA6oNzzqmR7nGH1J94gRdB+Mbs3gQN+w3+8N0WyfLBb5GJOZv+mWKyAI4gAr3UYvpXrvT/w0CLmfjGwGPa9HZiTfc1HXquFxj3pgo3ZzUpylWB/2BcMw+5PAx9qsLp3rYZfMz1zpyQF1HZhg5eR52K1U3Q8zU6bUkFql4OVZzBlOLwGc48O7kh+CdopGJQPT/fJVMpKnuaQN26jIjkO/4lcaberNw/iknENUXgIdNUZaJUrTck2Fosf0lDXFVkyTnIsupRBrRvW8I0BkSgumuNZ5HYMCVh/UQkA3u0=
notifications:
  pushover:
    api_key:
      secure: JC3aejPBM7YW9qFcUvveGQuQeoMfZE52e2Kqxme5JM7bP0K7nZJD+8BWOAoSoeCkks5/xLo8MJYOzHdt189ZYoCtOz27LLYzVX5t4HUxe6mZm+nGR/ZFHFRzuiXbw724/p2olWVT3Mouvb8vPiaUdOyvFR7Q94vNbqAUIFWEi44ySi/KIKXrkvnPPHtvWOIuLcmYcf95FpgJ+eU/vOAqo2Cs+0H+49DtwR1B97Rur0w3/kTPJy0kvn/zbGQ/L5qG7RNwXJe4sLRbbYuVYyXMKCo7aCExL8GpFleLb//1yFQl9hzFvE2+GwuQS7pBk09LHuBwql5YhFAff6UZZyDnLgF8C8CQ6/W5Zn3Ddg4pRwHFBeZXIgO29Yw70/n0whHtRR2nUfdbLSL8wEUkx8j9sYNDQBFjSNoq7AiNj3yZFsX4A9Jp13/3WTM1nNM+orhrR6yVG6BMxUDgO0VZxGK1PsnOv3kk9Si67zVEuHonXgeiV7eNkS5l52Kv29LH42W4773LtamcZPCm24/nzcfAM3EZxGR93O3NGC/XoYBupvr3QJ3DE12io0h8eK+akdx2aVp1Z0fh4nSjLAuhBAm4OtGm/+RTVEFZrXVmBNQVu8ndFg/yYYKvjnTEdB68E/BtklPu+0rV8PbzaImkIiWIBwcGUsa30RYCCdkQJ4jwoTA=
    users:
      secure: G3Z9i5K6xPAGlntRn6xlCtTGDl1Nt5WOt9MRbIgpczu7BtHJnsOWAVRbPJQgJZvxmsFVL24c03vfKg9jiTcz3De41yKCCFzVtZXjweOVgNUzwdfbOVsb9p8U21oea8QWsoDskdYcG9QiRq48GsW/kb7E83G5BROsUiGcPxTwAohhAqgy8dj0Ke93vBjJK/a8iJJ3if/yC8SNxClsm5kmWhUnPF8TqUR6ybaEEy76AWbzJetdzX4yNkctMOVKrl8Db6rsAc82kWVKnQ77bDOOQdGeNmiZMKyQVyr58pQWAXvxx2Y2KE3AFVHm8F8pjKiExLBDaikxExwYI6seEGIgZqQo0FvuNh35KNS4dL9mfhRBiETrW95MoIm8uyVAHEpWP8HOg/XX1xVUDQehndj5uKmS1UVkJ15q74kth3oKflS8yVfyNe/Q0mCc0Qcq4F2XnBYICAO3wcOws2QfXXs0TS8oeJox8xXVZJHhNYCWao1jlNXQh2L1/BseufZCsPvUIJQRY2iePAKhaWX4brzZBHSmioGuhODIJDRHOELZYowcsk3HXuFOhSOhtHqyVrYf/me0FBir+ezlRyeKyrbJhGRM8SaB6emVOd8cH6pER5tz8oWQr5+bkp4gwFhSUg4S/fxIxF6cB78bnVgrUGJ1X5C8Yyvocac7dE59D2IpDVQ=
