sudo: required
language: node_js
node_js:
- 8
services:
- docker
cache:
  directories:
  - node_modules
script:
- npm test
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "dev" ]]; then
  docker build -t cangr/mvs-explorer-api:dev .; docker push cangr/mvs-explorer-api:dev;
  fi
- if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then
  docker build -t cangr/mvs-explorer-api:latest .; docker push cangr/mvs-explorer-api:latest;
  fi
env:
  secure: LoucrImA+U1ByLLdiUa/ARxOgghW32baPugi7TdvBXzVkBNTO2cqc7cI1jaczQLxw+BfkIQRKViP+8j3ybKg5D0fvVoIePK/+B+zHW4cyJQplJrCWzSWTK0WefQuA3DQG1P+oVqYuJnOOOT16rwi8LHeFzJKmBIu1DgoSdmJVueB8FnDJXA9KTVEpnoJcdWxetfI7tKwvXPUpNsPokGS7tAwF03E0luTnX995zJYfgCPA0ADoUTNLb4ctMN3n5EkhbKshI5jvGEYlsNu2jezdux43W5qTAVq09D4ots21e3YCV4+gM3arnPHPKHaj2eOMuPzvvnCYWYUeppsI4MY7g+CeOpO856JZGK7416rhJc4uGLr/yaZS2oCOGdVxXSOH2p/1yj1lrXFTZQdVmrTs/pUpsdkmXaJ0qQUBn1NDO80sYzrEVVVd3fZ7skH19+vVnG/AYd1x37xAX3sfoo+8O5iHUB9I3WBIITbizzyKILGRr1OZXTihGSGO4DWdZcVuBsyy4wba4aeGGQMAYR4vS7il9Eu8VUJqu0LXwTinPpcsG2h01uKYT4+d0OsTGGIY1wNAgFV4MBan9gZ8yH1O9pyR86UQqWsb+dhSXSBtmPFXCyqVJdvgv98lhz300/e8iy/BM4CMlwZ9vkias/vTzicTDzCTV+OdAfNhqZdzGc=
notifications:
  pushover:
    api_key:
      secure: JC3aejPBM7YW9qFcUvveGQuQeoMfZE52e2Kqxme5JM7bP0K7nZJD+8BWOAoSoeCkks5/xLo8MJYOzHdt189ZYoCtOz27LLYzVX5t4HUxe6mZm+nGR/ZFHFRzuiXbw724/p2olWVT3Mouvb8vPiaUdOyvFR7Q94vNbqAUIFWEi44ySi/KIKXrkvnPPHtvWOIuLcmYcf95FpgJ+eU/vOAqo2Cs+0H+49DtwR1B97Rur0w3/kTPJy0kvn/zbGQ/L5qG7RNwXJe4sLRbbYuVYyXMKCo7aCExL8GpFleLb//1yFQl9hzFvE2+GwuQS7pBk09LHuBwql5YhFAff6UZZyDnLgF8C8CQ6/W5Zn3Ddg4pRwHFBeZXIgO29Yw70/n0whHtRR2nUfdbLSL8wEUkx8j9sYNDQBFjSNoq7AiNj3yZFsX4A9Jp13/3WTM1nNM+orhrR6yVG6BMxUDgO0VZxGK1PsnOv3kk9Si67zVEuHonXgeiV7eNkS5l52Kv29LH42W4773LtamcZPCm24/nzcfAM3EZxGR93O3NGC/XoYBupvr3QJ3DE12io0h8eK+akdx2aVp1Z0fh4nSjLAuhBAm4OtGm/+RTVEFZrXVmBNQVu8ndFg/yYYKvjnTEdB68E/BtklPu+0rV8PbzaImkIiWIBwcGUsa30RYCCdkQJ4jwoTA=
    users:
      secure: G3Z9i5K6xPAGlntRn6xlCtTGDl1Nt5WOt9MRbIgpczu7BtHJnsOWAVRbPJQgJZvxmsFVL24c03vfKg9jiTcz3De41yKCCFzVtZXjweOVgNUzwdfbOVsb9p8U21oea8QWsoDskdYcG9QiRq48GsW/kb7E83G5BROsUiGcPxTwAohhAqgy8dj0Ke93vBjJK/a8iJJ3if/yC8SNxClsm5kmWhUnPF8TqUR6ybaEEy76AWbzJetdzX4yNkctMOVKrl8Db6rsAc82kWVKnQ77bDOOQdGeNmiZMKyQVyr58pQWAXvxx2Y2KE3AFVHm8F8pjKiExLBDaikxExwYI6seEGIgZqQo0FvuNh35KNS4dL9mfhRBiETrW95MoIm8uyVAHEpWP8HOg/XX1xVUDQehndj5uKmS1UVkJ15q74kth3oKflS8yVfyNe/Q0mCc0Qcq4F2XnBYICAO3wcOws2QfXXs0TS8oeJox8xXVZJHhNYCWao1jlNXQh2L1/BseufZCsPvUIJQRY2iePAKhaWX4brzZBHSmioGuhODIJDRHOELZYowcsk3HXuFOhSOhtHqyVrYf/me0FBir+ezlRyeKyrbJhGRM8SaB6emVOd8cH6pER5tz8oWQr5+bkp4gwFhSUg4S/fxIxF6cB78bnVgrUGJ1X5C8Yyvocac7dE59D2IpDVQ=
