sudo: required
language: node_js
node_js:
- 8
services:
- docker
cache:
  directories:
  - node_modules
script:
- npm test
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "dev" ]]; then
  docker build -t cangr/mvs-explorer-api:dev .; docker push cangr/mvs-explorer-api:dev;
  fi
- if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then
  docker build -t cangr/mvs-explorer-api:latest .; docker push cangr/mvs-explorer-api:latest;
  fi
env:
  - secure: Gmt7ug7e2RCyXP9nR4WB0vkeQy+wZKpvEiw20ILNvaJHUu3MZ4tPiwfB6B+tGQ8EJu8rAZwitU1vrEngv15wSEKTIXHOJt9XW3rv97QFLWjUsUd6n9N6WAPPCuTXhgyZTZHPP/s4vkriP6yo+g+bUT59QJFfRHkXUBB0kecbaMEHgQsM6Is6+SUkAAxDu1O8Ed0LsQQtgu3rowoKi0heazHLsQJfrBIvnECbhbJsjIC9/caSwbau1oZa2SKYkK3+Y0OgmOk+L6S+aFqrvgufwrprydLzTlRktsyFJnSi6eaC4/Bt8HPBSqooHDkbXuRvg0p0lx+7lLqCFbJrVv6Kglo6vMFsuz+5fx9dEgtoJ31Th694fSWlnJ4EIwJWB467vMufQRCwe1H7dqnbDVvZx3MACdcxc7XaReUvMduk6DgifN7Ew6pN+BJl/4e8vXeysfNHFgQoKUZcF6txZJkVLVXNsQ16N9x0D0qCIA6tU9oh7nMim/+kCSwzY+0odmyiXAaMi5R6mkOb8+kZjbSI5vfYC5pdw96idExmnhcoCAaknqdfwwEIVa+gsn5/0sX8Rlb+G9yE5bMULU7t74Ufkd2vZwfoqkU/7KjiyZ8CZIKqTdlUzZougRHuhutG6eAPbIWi90y646KC+J2VfqwqcisOqxt4+7WiuDpAYY690Wg=
  - secure: tMixpn+xsWMc2lvH6poRioXSZhykCVqwx2TvKe+6LGZPfFhvmo6OFpLouA+J2zIud7hS0BkLKyOuPefLbSJfuP0c7IBVkLof85T69qZNgIxkX8Pz9eF9BqTGcfQD/dPBs5WI06rOEyFQ20oZDx3T2m5dvnXGyLAhS7jVNl28ZNqj7Z7m8+1/mmByv7UdP5Fw80hM1SUqapN9jyRDL0PJGw1MhAyvaXnyvWEEi9pjpsbUfOG70PhZO7zjbPfkMoGpPSARz8D09JnhDO61CtNbb5UFzMOJOYbm5ElzeWwcoDmN/J4NCWK66S34nkG3yAuP793TivurcuvAzqVOMfmQWC6YBsde14fXJxazfiNmjER85S9PNK2zLCiY2QGfc0vibMqPp5LzdRQOlF+eD9OdpCv/WjxU6SiQtYC/ipXAQ/t3t6FMBUT2VnKaPyamQAsSsZaXHSkKwS0dTm6QwXqH3ho3zpNn+4uoJpbtJT0tYFh3bw5/DMsvbSFqXvMf33V5e5rfKhk8AiSSHW+W9XLZ6uK+8Xbnifqgc4TNoO4aTs3fPQFdkmAv0IiuBeCyzJrKUOAcNhe6VuPt72L2cb2hUpjOl3XAEAfs/2yFMjkdQUtikPeaW1Qo/G0yT2O1tP6qlkQxwblaCofK/4HFIKhM6RFZtMiR4HcrF8qD+eW0uEI=
notifications:
  pushover:
    api_key:
      secure: JC3aejPBM7YW9qFcUvveGQuQeoMfZE52e2Kqxme5JM7bP0K7nZJD+8BWOAoSoeCkks5/xLo8MJYOzHdt189ZYoCtOz27LLYzVX5t4HUxe6mZm+nGR/ZFHFRzuiXbw724/p2olWVT3Mouvb8vPiaUdOyvFR7Q94vNbqAUIFWEi44ySi/KIKXrkvnPPHtvWOIuLcmYcf95FpgJ+eU/vOAqo2Cs+0H+49DtwR1B97Rur0w3/kTPJy0kvn/zbGQ/L5qG7RNwXJe4sLRbbYuVYyXMKCo7aCExL8GpFleLb//1yFQl9hzFvE2+GwuQS7pBk09LHuBwql5YhFAff6UZZyDnLgF8C8CQ6/W5Zn3Ddg4pRwHFBeZXIgO29Yw70/n0whHtRR2nUfdbLSL8wEUkx8j9sYNDQBFjSNoq7AiNj3yZFsX4A9Jp13/3WTM1nNM+orhrR6yVG6BMxUDgO0VZxGK1PsnOv3kk9Si67zVEuHonXgeiV7eNkS5l52Kv29LH42W4773LtamcZPCm24/nzcfAM3EZxGR93O3NGC/XoYBupvr3QJ3DE12io0h8eK+akdx2aVp1Z0fh4nSjLAuhBAm4OtGm/+RTVEFZrXVmBNQVu8ndFg/yYYKvjnTEdB68E/BtklPu+0rV8PbzaImkIiWIBwcGUsa30RYCCdkQJ4jwoTA=
    users:
      secure: G3Z9i5K6xPAGlntRn6xlCtTGDl1Nt5WOt9MRbIgpczu7BtHJnsOWAVRbPJQgJZvxmsFVL24c03vfKg9jiTcz3De41yKCCFzVtZXjweOVgNUzwdfbOVsb9p8U21oea8QWsoDskdYcG9QiRq48GsW/kb7E83G5BROsUiGcPxTwAohhAqgy8dj0Ke93vBjJK/a8iJJ3if/yC8SNxClsm5kmWhUnPF8TqUR6ybaEEy76AWbzJetdzX4yNkctMOVKrl8Db6rsAc82kWVKnQ77bDOOQdGeNmiZMKyQVyr58pQWAXvxx2Y2KE3AFVHm8F8pjKiExLBDaikxExwYI6seEGIgZqQo0FvuNh35KNS4dL9mfhRBiETrW95MoIm8uyVAHEpWP8HOg/XX1xVUDQehndj5uKmS1UVkJ15q74kth3oKflS8yVfyNe/Q0mCc0Qcq4F2XnBYICAO3wcOws2QfXXs0TS8oeJox8xXVZJHhNYCWao1jlNXQh2L1/BseufZCsPvUIJQRY2iePAKhaWX4brzZBHSmioGuhODIJDRHOELZYowcsk3HXuFOhSOhtHqyVrYf/me0FBir+ezlRyeKyrbJhGRM8SaB6emVOd8cH6pER5tz8oWQr5+bkp4gwFhSUg4S/fxIxF6cB78bnVgrUGJ1X5C8Yyvocac7dE59D2IpDVQ=
